---
# Установка пакетов, используя модуль apt
    - name: Install apcahe+php modules 
      apt:
          name: "{{ item }}" 
          update_cache: yes
          state: latest
      with_items: "{{ packages }}" # Используем with_items, если нужно установить массив пакетов

# Запуск сервиса, используя модуль service
    - name: Start apache2 service
      service:
          name: apache2
          state: started
          enabled: yes

# Аналог команды wget, используя модуль get_url
    - name: programm packages
      get_url:
          url: "{{ programmurl }}"
          dest: "{{ programmdir }}"
          mode: "0777"

# Распаковка установленного пакета, используя модуль 
    - name: Dpkg programm package
      dpkg_selections:
        name: "{{ programmpkg }}"
        selection: hold # Hold - установка без обновления пакета