# Create molecule test for playbook, image platform: centos:7 (cover with tests as much you can)

- name: Install ntp
  yum:
    name: ntp
    state: present
    
    
- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
    
    
- name: Install http and php etc
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - httpd
   - php
   - php-mysql
   - git
   - libsemanage-python
   - libselinux-python
  
- name: http service state
  service:  
    name: httpd
    state: started
    enabled: yes
    
- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  when: sestatus.rc != 0
  
- name: Install Mysql package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port 
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: sestatus.rc != 0 

- name: Start Mysql Service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db:
    name: "tpt_db"
    state: present
    
   
